name: Auto-Sync AR-ToolKit

on:
  schedule:
    # Check for updates every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual trigger
  repository_dispatch:
    # Allow external trigger from AR-ToolKit repo

jobs:
  sync-ar-toolkit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add AR-ToolKit remote
        run: |
          git remote add ar-toolkit https://github.com/CVO-TreeAi/AR-ToolKit.git || true

      - name: Fetch AR-ToolKit updates
        run: git fetch ar-toolkit main

      - name: Check for updates
        id: check-updates
        run: |
          if git diff --quiet HEAD ar-toolkit/main; then
            echo "has-updates=false" >> $GITHUB_OUTPUT
          else
            echo "has-updates=true" >> $GITHUB_OUTPUT
          fi

      - name: Sync AR-ToolKit updates
        if: steps.check-updates.outputs.has-updates == 'true'
        run: |
          git subtree pull --prefix=ar-toolkit ar-toolkit main --squash -m "Auto-sync: Update AR-ToolKit from upstream"

      - name: Push changes
        if: steps.check-updates.outputs.has-updates == 'true'
        run: git push origin main